### ISSUE TITLE
The plugin does not install for logstash 5.0.2

### ISSUE THREAD

**Issue by shubhendu-shekhar** [logstash-plugins/logstash-input-websocket#11]
I've been trying to install logstash-input-websocket using the command 
`bin/logstash-plugin install logstash-input-websocket` 

Every time I try to do that, I get an error. PFB the image. 

![image](https://cloud.githubusercontent.com/assets/17598162/20914514/14a63ebc-bba6-11e6-9441-f0e013765aeb.png)

- Version: Logstash 5.0.2
- Operating System: OpenSUSE 13.2
- Steps to Reproduce: Try and install the plugin.

**Comment by magnusbaeck** [comment]
Indeed, this plugin hasn't been updated to support the new event API in Logstash 5. Making the necessary adaptations should be very simple, though.

**Comment by shubhendu-shekhar** [comment]
Hi, can you please guide me through it. I'm quite new to Logstash and would really appreciate your help on this

**Comment by magnusbaeck** [comment]
Available in v4.0.0 of the plugin, available from rubygems.org.
