### ISSUE TITLE
keep generating TCP connections with CLOSE_WAIT state

### ISSUE THREAD

**Issue by minimax90** [logstash-plugins/logstash-input-websocket#20]
For all general issues, please provide the following details for fast resolution:

- Version: logstash 6.5.3, logstash-input-websocket 4.0.4
- Operating System: Ubuntu 16.04.5 LTS
- Config File (if you have sensitive info, please remove it):
input {
    websocket {
        mode => "client"
        url => "ws://xxxxxxxxxxxxxxxxxxxxx:80/app?token=yyyyyyyyyyyyyyyyyyy#"
    }
}

- Steps to Reproduce:
I am using websocket input to get data from a remote websocket server. However, the number of TCP connections with CLOSE_WAIT state keep increasing if there is exception thrown (e.g, the remote server unreachable for a while). 
1. check /var/log/logstash/logstash-plain.log:
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x2a9b0bf5>>}
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x6d4d385c>>}
[WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x2c03c447>>}
................

2. check the tcp connection:
netstat -ntp
Proto Recv-Q Send-Q Local Address                 Foreign Address                 State       PID/Program name
tcp6       1      0  <local_server_IP>:56712      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:49290      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:51528      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:59730      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
tcp6       1      0  <local_server_IP>:46522      <websocket_server_IP>:80        CLOSE_WAIT  14515/java
......................

3. finally the number of CLOSE_WAIT connections will be many (e.g 15000+), and logstash stops working due to excessive number of connections. I have to restart the logstash service.

I wonder if there is a bug in the current retry logic? Thanks.

**Comment by magnusbaeck** [comment]
Yes, it's a socket leak in websocket.rb, but AFAICT the FTW library used as the websocket client doesn't provide the ability to close the websocket connection. I've filed https://github.com/jordansissel/ruby-ftw/issues/45 for that. Let's see what response that issue brings.

**Comment by magnusbaeck** [comment]
Oh, and I filed #21 for the NoMethodError exception itself.

**Comment by romain-chanu** [comment]
@magnusbaeck - FYI, From the `Agent` class, it is possible to [shutdown](https://www.rubydoc.info/gems/ftw/0.0.49/FTW/Agent#shutdown-instance_method) all the active connections.

**Comment by magnusbaeck** [comment]
Thanks for the pointer! I overlooked that method. In that case the patch should be rather trivial.
