### ISSUE TITLE
Don't assume that FTW::Agent.websocket! always returns a FTW::WebSocket object

### ISSUE THREAD

**Issue by magnusbaeck** [logstash-plugins/logstash-input-websocket#21]
The code assumes that FTW::Agent.websocket! always returns a FTW::WebSocket object that we can call `each` on, but that's only true if the websocket handshake is successful. Because of this flawed assumption we get this, which is not only ugly but also hides the actual response that might contain information useful for debugging:

    [WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #FTW::Response:0x2c03c447>}

This was originally seen and reported in #20.

**Comment by minimax90** [comment]
Is there any fix for this bug?

**Comment by minimax90** [comment]
@magnusbaeck May I know is there any fix for this bug?

**Comment by magnusbaeck** [comment]
> May I know is there any fix for this bug?

In general any available fixes should be visible in the issue, making additional questions less than useful, but as it happens a PR that addresses this bug was just opened so I hope we'll be able to close this issue pretty soon (but the holidays could cause delays).
