### ISSUE TITLE
Plugin doesn't work : "Errno::EBADF: Bad file descriptor - Bad file descriptor"

### ISSUE THREAD

**Issue by pilebones** [logstash-plugins/logstash-input-websocket#7]
I tried with Logstash version 2.1 (With an official Docker Container from here : https://hub.docker.com/_/logstash/)

And I installed this "input-websocket" plugin :
```bash
/opt/logstash/bin/plugin install --version 2.0.2 logstash-input-websocket
```
With this following Logstash's setting :

```bash
input {
  websocket {
    url => "ws://127.0.0.1:3232"
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch { 
    hosts => ["elasticsearch:9200"] 
  }
```

When I run Logstash, I obtained this error message  :
```bash
websocket input client threw exception, restarting {:exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :level=>:warn}
```

I already tried with Logstash v1.5 and "input-websocket" v0.1.X, and I still have the same problem. What's wrong with this plugin ?

Note : Default configuration (from https://www.elastic.co/guide/en/logstash/2.1/plugins-inputs-websocket.html) doesn't work, ie :
```bash
input {
  websocket {
  }
}
``` 
=> Error message : "Addressable::URI::InvalidURIError: Hostname not supplied: '0.0.0.0'"

Could you help me please ?

Please find my entire Logstash's settings here : https://github.com/pilebones/elk-stack-docker/tree/logstash-with-input-websocket-plugin

**Comment by magnusbaeck** [comment]
I'm sorry but I have to ask—are you 100% sure you have a websocket server responding on port 3232? I just tested the plugin (2.0.2 with Logstash 2.1) and it works fine against https://github.com/dpallot/simple-websocket-server but if I shut down the server I get exactly the same error message that you get. Also, what kind of websocket server is it?

I've extracted your comment about the default configuration into #8.

**Comment by magnusbaeck** [comment]
I've realized that an upstream library can't cope with path-less URLs (a bug tracked in https://github.com/jordansissel/ruby-ftw/issues/29). Could you please try adding a trailing slash to your URL, i.e. use ws://127.0.0.1:3232/ instead of ws://127.0.0.1:3232?

**Comment by pilebones** [comment]
Thanks for your feedbacks. 

So, I wished to have a Logstash server wich listen on port 3232 with websocket to send my logs inside from my application. I don't have any other server which listenning on this port. This is why I set up :
```
input {
  websocket {
    url => "ws://127.0.0.1:3232"
  }
}
```

I didn't want a logstash-input-websocket as client. Maybe the server mode can answer my need, but I use tcp-input instead of websocket-input. I reckon I didn't understand the vocation of this plugin, sorry. 

You could close this issue, thank you.

**Comment by magnusbaeck** [comment]
> So, I wished to have a Logstash server wich listen on port 3232 with websocket to send my logs inside from my application.

Yeah, you'd need server mode for that but it isn't supported yet (see #2).
